### ISSUE TITLE
Add as many people as possible as admins and members of the repo to ensure there are plenty of people with access to the repo

### ISSUE THREAD

**Issue by matt-oakes** [buildbrighton/build-brighton-website#6]
* `alexanderhosford`
* `gViro`

**Comment by gViro** [comment]
yes...this. 
the website had really suffered from lack of administration.
thanks

**Comment by matt-oakes** [comment]
Covered by the repo being in the organisation. Anyone with "member" or above will be able to merge changes and Netlify will automatically release the changes.
